export const overviewMetrics = [
  {
    label: "Requests",
    value: "128",
    change: "+18.5%",
    detail: "vs previous period",
  },
  {
    label: "Avg. latency",
    value: "1.84s",
    change: "-12.4%",
    detail: "faster than previous period",
  },
  {
    label: "Fallback rate",
    value: "6.3%",
    change: "-2.1%",
    detail: "requests requiring fallback",
  },
];

export const recentRequests = [
  {
    id: "req_01",
    prompt: "Summarize the latest support ticket themes",
    taskType: "SUMMARIZATION",
    complexity: "LOW",
    routedModel: "Gemini 2.5 Flash",
    routedProvider: "Google",
    executedModel: "Gemini 2.5 Flash",
    executedProvider: "Google",
    fallbackUsed: false,
    latency: "842 ms",
    status: "Success",
    time: "2 min ago",
  },
  {
    id: "req_02",
    prompt: "Refactor this TypeScript service for better reliability",
    taskType: "CODING",
    complexity: "HIGH",
    routedModel: "Claude Sonnet 5",
    routedProvider: "Anthropic",
    executedModel: "Claude Sonnet 5",
    executedProvider: "Anthropic",
    fallbackUsed: false,
    latency: "2.16 s",
    status: "Success",
    time: "14 min ago",
  },
  {
    id: "req_03",
    prompt: "Explain caching strategy for a high traffic web application",
    taskType: "REASONING",
    complexity: "LOW",
    routedModel: "Gemini 2.5 Flash",
    routedProvider: "Google",
    executedModel: "Claude Sonnet 5",
    executedProvider: "Anthropic",
    fallbackUsed: true,
    latency: "2.11 s",
    status: "Fallback",
    time: "31 min ago",
  },
  {
    id: "req_04",
    prompt: "Extract the company names and revenue values",
    taskType: "EXTRACTION",
    complexity: "LOW",
    routedModel: "GPT-5 Nano",
    routedProvider: "OpenAI",
    executedModel: "GPT-5 Nano",
    executedProvider: "OpenAI",
    fallbackUsed: false,
    latency: "1.02 s",
    status: "Success",
    time: "1 hr ago",
  },
];

export const modelActivity = [
  {
    model: "Gemini 2.5 Flash",
    provider: "Google",
    share: 42,
    requests: 54,
  },
  {
    model: "Claude Sonnet 5",
    provider: "Anthropic",
    share: 34,
    requests: 44,
  },
  {
    model: "GPT-5 Nano",
    provider: "OpenAI",
    share: 24,
    requests: 30,
  },
];